{% set name = "clusterCleaver" %}
{% set version = "0.0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/clustercleaver-{{ version }}.tar.gz
  sha256: c5786c14ae9cd8a496955da4fff794dc28393b034b664752beb935f5167554d3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - scanpy >=1.9.8
    - scipy >=1.12.0
    - matplotlib-base >=3.8
    - numpy >=1.26.3
    - seaborn >=0.13.2
    - tqdm >=4.66.1
    - pandas >=2.2.0

test:
  imports:
    - clusterCleaver
  commands:
    - pip check
  requires:
    - pip

about:
  home: "https://github.com/brocklab/clusterCleaver"
  summary: Separate your clusters with gene distance
  license: MIT
  license_file: license.txt

extra:
  recipe-maintainers:
    - daylinmorgan
